version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - .venv
          key: v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: pytest

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install black
          command: pip install black
      - run:
          name: Check code formatting
          command: black --check .

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - lint